export const modSections = [
  //AdvSolarPanel
  {
    id: "AdvancedSolarPanel",
    title: "Advanced Solar Panel",
    icon: "./icons/advsolar.png",
    items: [
      {
        id: "30831:9",
        name: "Sunnarium part",
        image: "https://mixicons.zrefio.com/api/items/4081/32/",
        quantity: "≤ 32",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831",
        name: "Sunnarium",
        image: "https://mixicons.zrefio.com/api/items/4064/32/",
        quantity: "≤ 9",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:1",
        name: "Sunnarium Alloy",
        image: "https://mixicons.zrefio.com/api/items/4073/32/",
        quantity: "1",
        cost: "≥ 6 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:6",
        name: "Iridium Iron Plate",
        image: "https://mixicons.zrefio.com/api/items/4078/32/",
        quantity: "≤ 4",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:7",
        name: "Reinforced Iridium Iron Plate",
        image: "https://mixicons.zrefio.com/api/items/4079/32/",
        quantity: "1",
        cost: "≥ 8 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:8",
        name: "Irradiant Reinforced Plate",
        image: "https://mixicons.zrefio.com/api/items/4080/32/",
        quantity: "1",
        cost: "≥ 8 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:11",
        name: "Слиток титана",
        image: "https://mixicons.zrefio.com/api/items/4066/32/",
        quantity: "1",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:12",
        name: "Titanium Plate",
        image: "https://mixicons.zrefio.com/api/items/4067/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:13",
        name: "Titanium Lense",
        image: "https://mixicons.zrefio.com/api/items/4068/32/",
        quantity: "1",
        cost: "≥ 6 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:16",
        name: "Photon Buffer",
        image: "https://mixicons.zrefio.com/api/items/4071/32/",
        quantity: "1",
        cost: "≥ 20 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:15",
        name: "Quantum Processor Cooling",
        image: "https://mixicons.zrefio.com/api/items/4070/32/",
        quantity: "1",
        cost: "≥ 24 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:14",
        name: "Quantum Processor",
        image: "https://mixicons.zrefio.com/api/items/4069/32/",
        quantity: "1",
        cost: "≥ 24 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30831:17",
        name: "Moonlight Filter",
        image: "https://mixicons.zrefio.com/api/items/4072/32/",
        quantity: "1",
        cost: "≥ 8 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "246:3",
        name: "Solar Panel",
        image: "https://mixicons.zrefio.com/api/items/3595/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "194",
        name: "Advanced Solar Panel",
        image: "https://mixicons.zrefio.com/api/items/3506/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "194:1",
        name: "Hybrid Solar Panel",
        image: "https://mixicons.zrefio.com/api/items/3507/32/",
        quantity: "1",
        cost: "≥ 12 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "194:2",
        name: "Ultimate Solar Panel",
        image: "https://mixicons.zrefio.com/api/items/3508/32/",
        quantity: "1",
        cost: "≥ 9 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "194:4",
        name: "Quantum Solar Panel",
        image: "https://mixicons.zrefio.com/api/items/3510/32/",
        quantity: "1",
        cost: "≥ 8 конц. уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3555/32/",
      },
      {
        id: "194:6",
        name: "Solaris Titan Panel",
        image: "https://mixicons.zrefio.com/api/items/3512/32/",
        quantity: "1",
        cost: "≥ 32 конц. уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3555/32/",
      },
      {
        id: "194:7",
        name: "Eclipse Solar Panel",
        image: "https://mixicons.zrefio.com/api/items/3513/32/",
        quantity: "1",
        cost: "≥ 128 конц. уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3555/32/",
      },
      {
        id: "30832",
        name: "Advanced Solar Helmet",
        image: "https://mixicons.zrefio.com/api/items/4082/32/",
        quantity: "1",
        cost: "≥ 6 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30833",
        name: "Hybrid Solar Helmet",
        image: "https://mixicons.zrefio.com/api/items/4084/32/",
        quantity: "1",
        cost: "≥ 18 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30834",
        name: "Ultimate Solar Helmet",
        image: "https://mixicons.zrefio.com/api/items/4086/32/",
        quantity: "1",
        cost: "≥ 10 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
    ],
  },
  //IC2
  {
    id: "IndustrialCraft",
    title: "Industrial Craft",
    icon: "./icons/ic2.png",
    items: [
      {
        id: "223",
        name: "Телепортер",
        image: "https://mixicons.zrefio.com/api/items/3548/32/",
        quantity: "1",
        cost: "≥ 6 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "223:1",
        name: "Катушка теслы",
        image: "https://mixicons.zrefio.com/api/items/3549/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "225",
        name: "Сейф",
        image: "https://mixicons.zrefio.com/api/items/3560/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "223:2",
        name: "Автосадовник",
        image: "https://mixicons.zrefio.com/api/items/3550/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "227",
        name: "Бат-Бокс",
        image: "https://mixicons.zrefio.com/api/items/3571/32/",
        quantity: "≤ 3",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "227:3",
        name: "Трансформатор НН",
        image: "https://mixicons.zrefio.com/api/items/3574/32/",
        quantity: "≤ 5",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "227:4",
        name: "Трансформатор СН",
        image: "https://mixicons.zrefio.com/api/items/3575/32/",
        quantity: "≤ 3",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "227:5",
        name: "Трансформатор ВН",
        image: "https://mixicons.zrefio.com/api/items/3576/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "227:2",
        name: "ЭХО/МФСУ",
        image: "https://mixicons.zrefio.com/api/items/3573/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "227:1",
        name: "МФЭ",
        image: "https://mixicons.zrefio.com/api/items/3572/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "250:12",
        name: "Улучшенный механизм",
        image: "https://mixicons.zrefio.com/api/items/3607/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "246",
        name: "Генератор",
        image: "https://mixicons.zrefio.com/api/items/3592/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "246:1",
        name: "Геотермальный генератор",
        image: "https://mixicons.zrefio.com/api/items/3593/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "246:2",
        name: "Водяная мельница",
        image: "https://mixicons.zrefio.com/api/items/3594/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "246:4",
        name: "Ветряк",
        image: "https://mixicons.zrefio.com/api/items/3596/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "233",
        name: "Блок ректора",
        image: "https://mixicons.zrefio.com/api/items/3581/32/",
        quantity: "≤ 3",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "246:5",
        name: "Ядерный реактор",
        image: "https://mixicons.zrefio.com/api/items/3597/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "225:1",
        name: "Торговый автомат",
        image: "https://mixicons.zrefio.com/api/items/3561/32/",
        quantity: "≤ 4",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "250:3",
        name: "Дробитель",
        image: "https://mixicons.zrefio.com/api/items/3613/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "250:2",
        name: "Электропечь",
        image: "https://mixicons.zrefio.com/api/items/3612/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "250:5",
        name: "Компрессор",
        image: "https://mixicons.zrefio.com/api/items/3615/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "250:4",
        name: "Экстрактор",
        image: "https://mixicons.zrefio.com/api/items/3614/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "250:11",
        name: "Утилизатор",
        image: "https://mixicons.zrefio.com/api/items/3606/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "250:13",
        name: "Индукционная печь",
        image: "https://mixicons.zrefio.com/api/items/3608/32/",
        quantity: "≤ 1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "250:14",
        name: "Генератор материи",
        image: "https://mixicons.zrefio.com/api/items/3609/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30109",
        name: "Хмель",
        image: "https://mixicons.zrefio.com/api/items/3753/32/",
        quantity: "≤ 2",
        cost: "≥1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30107",
        name: "Пиво бога/Zero",
        image: "https://mixicons.zrefio.com/api/items/3751/32/",
        quantity: "1",
        cost: "≥ 16 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30114",
        name: "Земляной нарост",
        image: "https://mixicons.zrefio.com/api/items/3760/32/",
        quantity: "≤ 4",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30127",
        name: "Мультиранец",
        image: "https://mixicons.zrefio.com/api/items/3798/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30209",
        name: "Электрический реактивный ранец",
        image: "https://mixicons.zrefio.com/api/items/3906/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30149",
        name: "Нано-сабля",
        image: "https://mixicons.zrefio.com/api/items/3822/32/",
        quantity: "1",
        cost: "≥ 1 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30234",
        name: "Алмазный бур",
        image: "https://mixicons.zrefio.com/api/items/3935/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30235",
        name: "Шахтёрский бур",
        image: "https://mixicons.zrefio.com/api/items/3937/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30233",
        name: "Электропила",
        image: "https://mixicons.zrefio.com/api/items/3933/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30140",
        name: "Электроключ",
        image: "https://mixicons.zrefio.com/api/items/3812/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30124",
        name: "Соковыжималка",
        image: "https://mixicons.zrefio.com/api/items/3770/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30119",
        name: "Электрическая мотыга",
        image: "https://mixicons.zrefio.com/api/items/3765/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30240",
        name: "Мультикристалл",
        image: "https://mixicons.zrefio.com/api/items/3943/32/",
        quantity: "1",
        cost: "≥ 2 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30241",
        name: "Энергокристалл",
        image: "https://mixicons.zrefio.com/api/items/3945/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30191",
        name: "Электросхема",
        image: "https://mixicons.zrefio.com/api/items/3886/32/",
        quantity: "≤ 12",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30190",
        name: "Улучшенная электросхема",
        image: "https://mixicons.zrefio.com/api/items/3885/32/",
        quantity: "≤ 6",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30184:9",
        name: "Стекловолокно",
        image: "https://mixicons.zrefio.com/api/items/3879/32/",
        quantity: "≤ 21",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30242",
        name: "Аккумулятор",
        image: "https://mixicons.zrefio.com/api/items/3942/32/",
        quantity: "≤ 8",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30187",
        name: "Композит",
        image: "https://mixicons.zrefio.com/api/items/3882/32/",
        quantity: "≤ 5",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30150",
        name: "Углепластик",
        image: "https://mixicons.zrefio.com/api/items/3824/32/",
        quantity: "≤ 3",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30147",
        name: "Иридиевая плата",
        image: "https://mixicons.zrefio.com/api/items/3820/32/",
        quantity: "≤ 1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30125",
        name: "Апгрейд ускорителя",
        image: "https://mixicons.zrefio.com/api/items/3772/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30125:1",
        name: "Апгрейд трансформатора",
        image: "https://mixicons.zrefio.com/api/items/3773/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30125:2",
        name: "Апгрейд энергохранителя",
        image: "https://mixicons.zrefio.com/api/items/3774/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30178",
        name: "Нано-шлем",
        image: "https://mixicons.zrefio.com/api/items/3859/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30177",
        name: "Нано-кираса",
        image: "https://mixicons.zrefio.com/api/items/3857/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30176",
        name: "Нано-поножи",
        image: "https://mixicons.zrefio.com/api/items/3855/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30175",
        name: "Нано-ботинки",
        image: "https://mixicons.zrefio.com/api/items/3853/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30174",
        name: "Квантовый шлем",
        image: "https://mixicons.zrefio.com/api/items/3851/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30173",
        name: "Квантовая кираса",
        image: "https://mixicons.zrefio.com/api/items/3849/32/",
        quantity: "1",
        cost: "≥ 6 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30172",
        name: "Квантовые поножи",
        image: "https://mixicons.zrefio.com/api/items/3847/32/",
        quantity: "1",
        cost: "≥ 6 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30171",
        name: "Квантовые ботинки",
        image: "https://mixicons.zrefio.com/api/items/3845/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30078",
        name: "Прибор ночного видения",
        image: "https://mixicons.zrefio.com/api/items/3721/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
    ],
  },
  //GraviSuite
  {
    id: "GraviSuite",
    title: "Gravitation Suite",
    icon: "./icons/gravisuite.png",
    items: [
      {
        id: "30473",
        name: "Гравитационный нагрудник",
        image: "https://mixicons.zrefio.com/api/items/3964/32/",
        quantity: "1",
        cost: "≥ 48 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30474",
        name: "Совершенный мультиранец",
        image: "https://mixicons.zrefio.com/api/items/3966/32/",
        quantity: "1",
        cost: "≥ 9 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30475:1",
        name: "Сверхпроводник",
        image: "https://mixicons.zrefio.com/api/items/3969/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30477",
        name: "Разрушитель/Ваджра",
        image: "https://mixicons.zrefio.com/api/items/3975/32/",
        quantity: "1",
        cost: "≥ 63 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30478",
        name: "Продвинутый алмазный бур",
        image: "https://mixicons.zrefio.com/api/items/3977/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30479",
        name: "Продвинутая электропила",
        image: "https://mixicons.zrefio.com/api/items/3979/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30480",
        name: "Улучшенный мультиранец",
        image: "https://mixicons.zrefio.com/api/items/3981/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30481",
        name: "Улучшенный реактивный ранец",
        image: "https://mixicons.zrefio.com/api/items/3983/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30482",
        name: "Грави - инструмент",
        image: "https://mixicons.zrefio.com/api/items/3985/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30483",
        name: "Улучшенный нано-нагрудник",
        image: "https://mixicons.zrefio.com/api/items/3987/32/",
        quantity: "1",
        cost: "≥ 6 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
    ],
  },
  //Applied
  {
    id: "AppliedEnergistics",
    title: "Applied Energistics",
    icon: "./icons/applied.png",
    items: [
      {
        id: "902",
        name: "Крепкая кварцевая руда",
        image: "https://mixicons.zrefio.com/api/items/4641/32/",
        quantity: "1",
        cost: "3 кристалла кварца",
        costImage: "https://mixicons.zrefio.com/api/items/4364/32/",
      },
      {
        id: "902",
        name: "Крепкая кварцевая руда",
        image: "https://mixicons.zrefio.com/api/items/4641/32/",
        quantity: "2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4362:6",
        name: "Кристалл кварца",
        image: "https://mixicons.zrefio.com/api/items/4364/32/",
        quantity: "16",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4362:7",
        name: "Кварцевая пыль",
        image: "https://mixicons.zrefio.com/api/items/4365/32/",
        quantity: "16",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4362",
        name: "Конвертирующая матрица",
        image: "https://mixicons.zrefio.com/api/items/4344/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4362:4",
        name: "Беспроводной приёмник",
        image: "https://mixicons.zrefio.com/api/items/4362/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4362:20",
        name: "Незаконченный стандартный процессор",
        image: "https://mixicons.zrefio.com/api/items/4355/32/",
        quantity: "2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4362:18",
        name: "МЭ стандартный процессор",
        image: "https://mixicons.zrefio.com/api/items/4352/32/",
        quantity: "2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4362:21",
        name: "Незаконченный улучшенный процессор",
        image: "https://mixicons.zrefio.com/api/items/4356/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4362:19",
        name: "МЭ улучшенный процессор",
        image: "https://mixicons.zrefio.com/api/items/4353/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901:14",
        name: "МЭ кабель",
        image: "https://mixicons.zrefio.com/api/items/4631/32/",
        quantity: "8",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901:1",
        name: "МЭ точная импортирующая шина",
        image: "https://mixicons.zrefio.com/api/items/4633/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901",
        name: "МЭ точная экспортирующая шина",
        image: "https://mixicons.zrefio.com/api/items/4626/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "903:1",
        name: "МЭ интерактивная шина импорта",
        image: "https://mixicons.zrefio.com/api/items/4644/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "903",
        name: "МЭ интерактивная шина экспорта",
        image: "https://mixicons.zrefio.com/api/items/4643/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901:9",
        name: "МЭ шина взаимодействия",
        image: "https://mixicons.zrefio.com/api/items/4640/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901:15",
        name: "МЭ интерактивная шина взаимодействия",
        image: "https://mixicons.zrefio.com/api/items/4632/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901:4",
        name: "МЭ излучатель сигнала",
        image: "https://mixicons.zrefio.com/api/items/4635/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901:12",
        name: "МЭ монитор",
        image: "https://mixicons.zrefio.com/api/items/4629/32/",
        quantity: "1",
        cost: "≥ 4 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901:11",
        name: "МЭ сборочный монитор",
        image: "https://mixicons.zrefio.com/api/items/4628/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "900:6",
        name: "МЭ терминал доступа",
        image: "https://mixicons.zrefio.com/api/items/4622/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "900:5",
        name: "МЭ точка беспроводного доступа",
        image: "https://mixicons.zrefio.com/api/items/4621/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4361:5",
        name: "МЭ беспроводная точка доступа",
        image: "https://mixicons.zrefio.com/api/items/4341/32/",
        quantity: "1",
        cost: "≥ 9 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4362:5",
        name: "Усилитель сигнала",
        image: "https://mixicons.zrefio.com/api/items/4363/32/",
        quantity: "≤ 5",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "900:2",
        name: "МЭ контроллер",
        image: "https://mixicons.zrefio.com/api/items/4618/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "900:7",
        name: "МЭ сундук",
        image: "https://mixicons.zrefio.com/api/items/4623/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "900:3",
        name: "МЭ привод",
        image: "https://mixicons.zrefio.com/api/items/4619/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "900:8",
        name: "МЭ интерфейс",
        image: "https://mixicons.zrefio.com/api/items/4624/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "900:4",
        name: "МЭ кодировщик шаблонов",
        image: "https://mixicons.zrefio.com/api/items/4620/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901:7",
        name: "МЭ корпус сборочного цеха",
        image: "https://mixicons.zrefio.com/api/items/4638/32/",
        quantity: "4",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901:6",
        name: "МЭ тепловыводящий элемент",
        image: "https://mixicons.zrefio.com/api/items/4637/32/",
        quantity: "≤3",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "901:5",
        name: "МЭ сборочный процессор",
        image: "https://mixicons.zrefio.com/api/items/4636/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "900:1",
        name: "МЭ поставщик шаблонов",
        image: "https://mixicons.zrefio.com/api/items/4617/32/",
        quantity: "1",
        cost: "≥ 6 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4362:16",
        name: "МЭ шаблон крафта",
        image: "https://mixicons.zrefio.com/api/items/4350/32/",
        quantity: "≤5",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4361",
        name: "МЭ 1k хранилище",
        image: "https://mixicons.zrefio.com/api/items/4337/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4361:7",
        name: "МЭ 4k хранилище",
        image: "https://mixicons.zrefio.com/api/items/4339/32/",
        quantity: "1",
        cost: "≥ 8 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4361:1",
        name: "МЭ 16k хранилище",
        image: "https://mixicons.zrefio.com/api/items/4338/32/",
        quantity: "1",
        cost: "≥ 16 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4361:2",
        name: "МЭ 64k хранилище",
        image: "https://mixicons.zrefio.com/api/items/4339/32/",
        quantity: "1",
        cost: "≥ 32 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4361:8",
        name: "МЭ 512k Хранилище материи",
        image: "https://mixicons.zrefio.com/api/items/4343/32/",
        quantity: "1",
        cost: "≥ 15 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
    ],
  },
  //CompactWindmils
  {
    id: "CompactWindmils",
    title: "Compact Windmils",
    icon: "./icons/compactwindmils.png",
    items: [
      {
        id: "2790",
        name: "Ветряк сверхнизкого напряжения (СНН)",
        image: "https://mixicons.zrefio.com/api/items/3649/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "2790:1",
        name: "Ветряк низкого напряжения (НН)",
        image: "https://mixicons.zrefio.com/api/items/3650/32/",
        quantity: "1",
        cost: "≥ 7 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "2790:2",
        name: "Ветряк среднего напряжения (СН)",
        image: "https://mixicons.zrefio.com/api/items/3651/32/",
        quantity: "1",
        cost: "≥ 22 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "2790:3",
        name: "Ветряк высокого напряжения (ВН)",
        image: "https://mixicons.zrefio.com/api/items/3652/32/",
        quantity: "1",
        cost: "≥ 9 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "2790:4",
        name: "Ветряк сверхвысокого напряжения (СВН)",
        image: "https://mixicons.zrefio.com/api/items/3653/32/",
        quantity: "1",
        cost: "≥ 34 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "2790:5",
        name: "Ветряк квантового напряжения (КН)",
        image: "https://mixicons.zrefio.com/api/items/3654/32/",
        quantity: "1",
        cost: "≥ 15 конц. уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3555/32/",
      },
      {
        id: "27903",
        name: "Композитный ротор",
        image: "https://mixicons.zrefio.com/api/items/3648/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "27902",
        name: "Иридиевый ротор",
        image: "https://mixicons.zrefio.com/api/items/3647/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
    ],
  },
  //ChargePads
  {
    id: "ChargePads",
    title: "Charge Pads",
    icon: "./icons/chargepads.png",
    items: [
      {
        id: "3099",
        name: "Static Charge Pad",
        image: "https://mixicons.zrefio.com/api/items/4089/32/",
        quantity: 1,
        cost: "3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "3099:1",
        name: "Crytalizor Charge Pad",
        image: "https://mixicons.zrefio.com/api/items/4090/32/",
        quantity: 1,
        cost: "7 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "3099:2",
        name: "Lapotronic Charge Pad",
        image: "https://mixicons.zrefio.com/api/items/4091/32/",
        quantity: 1,
        cost: "27 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "3099:3",
        name: "Fission Charge Pad",
        image: "https://mixicons.zrefio.com/api/items/4092/32/",
        quantity: 1,
        cost: "45 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "20264",
        name: "Crystalizor Upgrade Kit",
        image: "https://mixicons.zrefio.com/api/items/3537/32/",
        quantity: 1,
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "20264:2",
        name: "Lapotronic Upgrade Kit",
        image: "https://mixicons.zrefio.com/api/items/3539/32/",
        quantity: 1,
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "20264:3",
        name: "Fission Upgrade Kit",
        image: "https://mixicons.zrefio.com/api/items/3540/32/",
        quantity: 1,
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "20264:1",
        name: "MFS Unit Upgrade",
        image: "https://mixicons.zrefio.com/api/items/3538/32/",
        quantity: 1,
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
    ],
  },
  //BuildCraft
  {
    id: "BuildCraft",
    title: "BuildCraft",
    icon: "./icons/buildcraft.png",
    items: [
      {
        id: "1510",
        name: "Редстоун - двигатель",
        image: "https://mixicons.zrefio.com/api/items/3283/32/",
        quantity: "≤ 19",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "1511",
        name: "Помпа",
        image: "https://mixicons.zrefio.com/api/items/3286/32/",
        quantity: "≤ 3",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "13298",
        name: "Капсула с нефтью",
        image: "https://mixicons.zrefio.com/api/items/2662/32/",
        quantity: "≤ 16",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "13299",
        name: "Капсула с топливом",
        image: "https://mixicons.zrefio.com/api/items/2663/32/",
        quantity: "≤ 16",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "0",
        name: "Капсула с любым др. топливом",
        image: "https://mixicons.zrefio.com/api/items/2660/32/",
        quantity: "≤ 16",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
    ],
  },
  {
    id: "ComboArmors",
    title: "Combo Armors",
    icon: "./icons/comboarmors.png",
    items: [
      {
        id: "30760",
        name: "Улучшенный Квантовый Шлем",
        modules: true,
        image: "https://mixicons.zrefio.com/api/items/4000/32/",
        quantity: "1",
        cost: "≥ 10 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30778",
        name: "Квантовая кираса с электрическим реактивным ранцем и мультиранцем",
        modules: true,
        image: "https://mixicons.zrefio.com/api/items/4034/32/",
        quantity: "1",
        cost: "≥ 9 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30762",
        name: "Улучшенные квантовые поножи",
        modules: true,
        image: "https://mixicons.zrefio.com/api/items/4004/32/",
        quantity: "1",
        cost: "≥ 7 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30782",
        name: "Электростатические квантовые ботинки",
        modules: true,
        image: "https://mixicons.zrefio.com/api/items/4042/32/",
        quantity: "1",
        cost: "≥ 7 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30760",
        name: "Улучшенный Квантовый Шлем",
        modules: false,
        image: "https://mixicons.zrefio.com/api/items/4000/32/",
        quantity: "1",
        cost: "≥ 7 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30778",
        name: "Квантовая кираса с электрическим реактивным ранцем и мультиранцем",
        modules: false,
        image: "https://mixicons.zrefio.com/api/items/4034/32/",
        quantity: "1",
        cost: "≥ 7 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30762",
        name: "Улучшенные квантовые поножи",
        modules: false,
        image: "https://mixicons.zrefio.com/api/items/4004/32/",
        quantity: "1",
        cost: "≥ 7 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30782",
        name: "Электростатические квантовые ботинки",
        modules: false,
        image: "https://mixicons.zrefio.com/api/items/4042/32/",
        quantity: "1",
        cost: "≥ 7 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30771",
        name: "Нанно-кираса с бат-паком",
        image: "https://mixicons.zrefio.com/api/items/4020/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30772",
        name: "Нано-кираса с мультиранцем",
        image: "https://mixicons.zrefio.com/api/items/4022/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30773",
        name: "Нано-кираса с электрическим реактивным ранцем",
        image: "https://mixicons.zrefio.com/api/items/4024/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30774",
        name: "Нано-кираса с электрическим реактивным ранцем и мультиранцем",
        image: "https://mixicons.zrefio.com/api/items/4026/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30775",
        name: "Квантовая кираса с бат-паком",
        image: "https://mixicons.zrefio.com/api/items/4028/32/",
        quantity: "1",
        cost: "≥ 6 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30776",
        name: "Квантовая кираса с мультиранцем",
        image: "https://mixicons.zrefio.com/api/items/4030/32/",
        quantity: "1",
        cost: "≥ 7 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30777",
        name: "Квантовая кираса с электрическим реактивным ранцем",
        image: "https://mixicons.zrefio.com/api/items/4032/32/",
        quantity: "1",
        cost: "≥ 8 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30778",
        name: "Квантовая кираса с электрическим реактивным ранцем и мультиранцем",
        image: "https://mixicons.zrefio.com/api/items/4034/32/",
        quantity: "1",
        cost: "≥ 10 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30756",
        name: "Улучшенный нано-шлем",
        image: "https://mixicons.zrefio.com/api/items/3992/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30757",
        name: "Улучшенная нано-кираса",
        image: "https://mixicons.zrefio.com/api/items/3994/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30758",
        name: "Улучшенные нано-поножи",
        image: "https://mixicons.zrefio.com/api/items/3996/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30759",
        name: "Улучшенные нано-ботинки",
        image: "https://mixicons.zrefio.com/api/items/3998/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30760",
        name: "Улучшенный квантовый шлем",
        image: "https://mixicons.zrefio.com/api/items/4000/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30761",
        name: "Улучшенная квантовая кираса",
        image: "https://mixicons.zrefio.com/api/items/4002/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30762",
        name: "Улучшенные квантовые поножи",
        image: "https://mixicons.zrefio.com/api/items/4004/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30763",
        name: "Улучшенные квантовые ботинки",
        image: "https://mixicons.zrefio.com/api/items/4006/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30764",
        name: "Улучшенный электрический реактивный ранец",
        image: "https://mixicons.zrefio.com/api/items/4008/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30765",
        name: "Улучшенный бат-пак",
        image: "https://mixicons.zrefio.com/api/items/4012/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30766",
        name: "Улучшенный мультиранец",
        image: "https://mixicons.zrefio.com/api/items/4012/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30779",
        name: "Продвинутый электрический реактивный ранец",
        image: "https://mixicons.zrefio.com/api/items/4036/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30780",
        name: "Мульти-электро реактивный ранец",
        image: "https://mixicons.zrefio.com/api/items/4038/32/",
        quantity: "1",
        cost: "≥ 6 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30767",
        name: "Улучшенный СП - шлем",
        image: "https://mixicons.zrefio.com/api/items/4014/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30769",
        name: "СП - нановолоконный шлем",
        image: "https://mixicons.zrefio.com/api/items/4016/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30769",
        name: "СП - нановолоконный шлем LV",
        image: "https://mixicons.zrefio.com/api/items/4016/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30769",
        name: "СП - нановолоконный шлем MV",
        image: "https://mixicons.zrefio.com/api/items/4016/32/",
        quantity: "1",
        cost: "≥ 17 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30769",
        name: "СП - нановолоконный шлем HV",
        image: "https://mixicons.zrefio.com/api/items/4016/32/",
        quantity: "1",
        cost: "≥ 11 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30770",
        name: "СП - квантовый шлем",
        image: "https://mixicons.zrefio.com/api/items/4018/32/",
        quantity: "1",
        cost: "≥ 5 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30770",
        name: "СП - квантовый шлем LV",
        image: "https://mixicons.zrefio.com/api/items/4018/32/",
        quantity: "1",
        cost: "≥ 9 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30770",
        name: "СП - квантовый шлем MV",
        image: "https://mixicons.zrefio.com/api/items/4018/32/",
        quantity: "1",
        cost: "≥ 21 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30770",
        name: "СП - квантовый шлем HV",
        image: "https://mixicons.zrefio.com/api/items/4018/32/",
        quantity: "1",
        cost: "≥ 12 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30768",
        name: "Улучшенные электростатические ботинки",
        image: "https://mixicons.zrefio.com/api/items/4015/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30781",
        name: "Электростатические нановолоконные ботинки",
        image: "https://mixicons.zrefio.com/api/items/4040/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30782",
        name: "Электростатические квантовые ботинки",
        image: "https://mixicons.zrefio.com/api/items/4042/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30783",
        name: "Модуль улучшения",
        image: "https://mixicons.zrefio.com/api/items/4044/32/",
        quantity: "≤ 2",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30786",
        name: "СП-модуль",
        image: "https://mixicons.zrefio.com/api/items/4047/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30796",
        name: "MV Solar Production Upgrade Module",
        image: "https://mixicons.zrefio.com/api/items/4059/32/",
        quantity: "1",
        cost: "≥ 4 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30795",
        name: "LV Solar Production Upgrade Module",
        image: "https://mixicons.zrefio.com/api/items/4058/32/",
        quantity: "1",
        cost: "≥ 17 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30797",
        name: "HV Solar Production Upgrade Module",
        image: "https://mixicons.zrefio.com/api/items/4060/32/",
        quantity: "1",
        cost: "≥ 11 уран. блоков",
        costImage: "https://mixicons.zrefio.com/api/items/3554/32/",
      },
      {
        id: "30791",
        name: "Модуль 'Продвинутый хранитель энергии'",
        image: "https://mixicons.zrefio.com/api/items/4053/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30792",
        name: "Модуль 'Мульти-электро хранитель энергии'",
        image: "https://mixicons.zrefio.com/api/items/4054/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30785",
        name: "Модуль 'Турбина для полёта'",
        image: "https://mixicons.zrefio.com/api/items/4046/32/",
        quantity: "1",
        cost: "≥ 3 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30788",
        name: "Модуль 'Временной'",
        image: "https://mixicons.zrefio.com/api/items/4049/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30787",
        name: "Модуль 'Статическое производство'",
        image: "https://mixicons.zrefio.com/api/items/4048/32/",
        quantity: "1",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30789",
        name: "Модуль 'Разряд'",
        image: "https://mixicons.zrefio.com/api/items/4050/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "4000",
        name: "Сборщик брони",
        image: "https://mixicons.zrefio.com/api/items/4308/32/",
        quantity: "1",
        cost: "≥ 2 урана",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
    ],
  },
  //BaseResources
  {
    id: "BaseResource",
    title: "Базовые ресурсы",
    icon: "./icons/baseresources.png",
    items: [
      {
        id: "30128",
        name: "Иридий",
        image: "https://mixicons.zrefio.com/api/items/3800/32/",
        quantity: "≤ 9",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30188",
        name: "Материя",
        image: "https://mixicons.zrefio.com/api/items/3883/32/",
        quantity: "≤ 64",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30216",
        name: "Резина",
        image: "https://mixicons.zrefio.com/api/items/3914/32/",
        quantity: "≤ 16 - 32",
        cost: "≥ 1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "129",
        name: "Изумрудная руда",
        image: "https://mixicons.zrefio.com/api/items/2626/32/",
        quantity: "1",
        cost: "≤ 64 материи",
        costImage: "https://mixicons.zrefio.com/api/items/3883/32/",
      },
      {
        id: "56",
        name: "Алмазная руда",
        image: "https://mixicons.zrefio.com/api/items/4576/32/",
        quantity: "1",
        cost: "≤ 32 материи",
        costImage: "https://mixicons.zrefio.com/api/items/3883/32/",
      },
      {
        id: "73",
        name: "Редстоун руда",
        image: "https://mixicons.zrefio.com/api/items/4595/32/",
        quantity: "1",
        cost: "≤ 21 материя",
        costImage: "https://mixicons.zrefio.com/api/items/3883/32/",
      },
      {
        id: "21",
        name: "Лазуритовая руда",
        image: "https://mixicons.zrefio.com/api/items/3545/32/",
        quantity: "1",
        cost: "≤ 21 материя",
        costImage: "https://mixicons.zrefio.com/api/items/3883/32/",
      },
      {
        id: "16",
        name: "Угольная руда",
        image: "https://mixicons.zrefio.com/api/items/3310/32/",
        quantity: "1",
        cost: "≤ 13 материи",
        costImage: "https://mixicons.zrefio.com/api/items/3883/32/",
      },
      {
        id: "153",
        name: "Кварцевая руда",
        image: "https://mixicons.zrefio.com/api/items/3301/32/",
        quantity: "1",
        cost: "≤ 8 материи",
        costImage: "https://mixicons.zrefio.com/api/items/3883/32/",
      },
      {
        id: "902",
        name: "Крепкая кварцевая руда",
        image: "https://mixicons.zrefio.com/api/items/4641/32/",
        quantity: "1",
        cost: "≤ 4 материи",
        costImage: "https://mixicons.zrefio.com/api/items/3883/32/",
      },
      {
        id: "5261",
        name: "Бронзовый слиток",
        image: "https://mixicons.zrefio.com/api/items/4526/32/",
        quantity: "≤ 32",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30248",
        name: "Медный слиток",
        image: "https://mixicons.zrefio.com/api/items/3953/32/",
        quantity: "≤ 64",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "30247",
        name: "Оловянный слиток",
        image: "https://mixicons.zrefio.com/api/items/3952/32/",
        quantity: "≤ 64",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "265",
        name: "Железный слиток",
        image: "https://mixicons.zrefio.com/api/items/3631/32/",
        quantity: "≤ 48",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "266",
        name: "Золотой слиток",
        image: "https://mixicons.zrefio.com/api/items/3632/32/",
        quantity: "≤ 48",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "406",
        name: "Кварц",
        image: "https://mixicons.zrefio.com/api/items/4315/32/",
        quantity: "≤ 48",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "348",
        name: "Светящаяся пыль",
        image: "https://mixicons.zrefio.com/api/items/4137/32/",
        quantity: "≤ 48 - 64",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "263",
        name: "Уголь",
        image: "https://mixicons.zrefio.com/api/items/3628/32/",
        quantity: "≤ 64",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "351:4",
        name: "Лазурит",
        image: "https://mixicons.zrefio.com/api/items/4150/32/",
        quantity: "≤ 64",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "331",
        name: "Редстоун пыль",
        image: "https://mixicons.zrefio.com/api/items/4119/32/",
        quantity: "≤ 64",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "388",
        name: "Изумруд",
        image: "https://mixicons.zrefio.com/api/items/4289/32/",
        quantity: "≤ 3",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "264",
        name: "Алмаз",
        image: "https://mixicons.zrefio.com/api/items/3630/32/",
        quantity: "≤ 7",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "14",
        name: "Золотая руда",
        image: "https://mixicons.zrefio.com/api/items/3274/32/",
        quantity: "≤ 25",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "15",
        name: "Железная руда",
        image: "https://mixicons.zrefio.com/api/items/3309/32/",
        quantity: "≤ 25",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "248",
        name: "Оловянная руда",
        image: "https://mixicons.zrefio.com/api/items/3599/32/",
        quantity: "≤ 48",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
      {
        id: "249",
        name: "Медная руда",
        image: "https://mixicons.zrefio.com/api/items/3600/32/",
        quantity: "≤ 48",
        cost: "1 уран",
        costImage: "https://mixicons.zrefio.com/api/items/3949/32/",
      },
    ],
  },
  //Exchange
  {
    id: "Exchange",
    title: "Обмен",
    icon: "./icons/exchange.png",
    items: [
      {
        id: "129",
        name: "Изумрудная руда",
        image: "https://mixicons.zrefio.com/api/items/2626/32/",
        quantity: "64",
        cost: "1 СВН",
        costImage: "https://mixicons.zrefio.com/api/items/3653/32/",
      },
      {
        id: "56",
        name: "Алмазная руда",
        image: "https://mixicons.zrefio.com/api/items/4576/32/",
        quantity: "64",
        cost: "2 ВН",
        costImage: "https://mixicons.zrefio.com/api/items/3652/32/",
      },
      {
        id: "902",
        name: "Крепкая кварцевая руда",
        image: "https://mixicons.zrefio.com/api/items/4641/32/",
        quantity: "64",
        cost: "1 ВН",
        costImage: "https://mixicons.zrefio.com/api/items/3652/32/",
      },
      {
        id: "153",
        name: "Кварцевая руда",
        image: "https://mixicons.zrefio.com/api/items/3301/32/",
        quantity: "64",
        cost: "3 СН",
        costImage: "https://mixicons.zrefio.com/api/items/3651/32/",
      },
      {
        id: "129",
        name: "Изумрудная руда",
        image: "https://mixicons.zrefio.com/api/items/2626/32/",
        quantity: "16",
        cost: "1 Ultimate Solar Panel",
        costImage: "https://mixicons.zrefio.com/api/items/3508/32/",
      },
      {
        id: "56",
        name: "Алмазная руда",
        image: "https://mixicons.zrefio.com/api/items/4576/32/",
        quantity: "32",
        cost: "1 Ultimate Solar Panel",
        costImage: "https://mixicons.zrefio.com/api/items/3508/32/",
      },
      {
        id: "902",
        name: "Крепкая кварцевая руда",
        image: "https://mixicons.zrefio.com/api/items/4641/32/",
        quantity: "64",
        cost: "1 Ultimate Solar Panel",
        costImage: "https://mixicons.zrefio.com/api/items/3508/32/",
      },
      {
        id: "153",
        name: "Кварцевая руда",
        image: "https://mixicons.zrefio.com/api/items/3301/32/",
        quantity: "64",
        cost: "3 Hybrid Solar Panel",
        costImage: "https://mixicons.zrefio.com/api/items/3507/32/",
      },
      {
        id: "194:2",
        name: "Ultimate Solar Panel",
        image: "https://mixicons.zrefio.com/api/items/3508/32/",
        quantity: "4",
        cost: "1 СВН",
        costImage: "https://mixicons.zrefio.com/api/items/3653/32/",
      },
      {
        id: "2790:4",
        name: "Ветряк сверхвысокого напряжения (СВН)",
        image: "https://mixicons.zrefio.com/api/items/3301/32/",
        quantity: "1",
        cost: "4 Ultimate Solar Panel",
        costImage: "https://mixicons.zrefio.com/api/items/3508/32/",
      },
    ],
  },
];
